branches:
  - name: "main"
  - name: "release/*"
    prerelease: "snapshot"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - [ "@semantic-release/changelog", { changelogFile: "CHANGELOG.md" } ]
  - "gradle-semantic-release-plugin"
  - [ '@semantic-release/exec', {
    prepareCmd: './gradlew :apollo:createSwiftPackage' } ]
  - [ '@semantic-release/exec', {
    prepareCmd: '(cd ./apollo/build/packages/ApolloSwift && zip -r "Apollo.xcframework.zip" Apollo.xcframework)' } ]
  - [ '@semantic-release/exec', {
    prepareCmd: "rm -f Package.swift && ./.scripts/updatePackage.swift 0.0.0 \"$(swift package compute-checksum 'apollo/build/packages/ApolloSwift/Apollo.xcframework.zip')\" ./.scripts/TemplatePackage.swift Package.swift" } ]
  - [
    "@semantic-release/git",
    {
      assets: [
        "Package.swift",
        "CHANGELOG.md",
        "gradle.properties",
      ],
      message: "chore(release): cut apollo version ${nextRelease.version}

        ${nextRelease.notes}",
    },
  ]
  - [
    "@semantic-release/github",
    {
      "assets": [
        { "path": "apollo/build/packages/ApolloSwift/Apollo.xcframework.zip", "label": "Apollo.xcframework.zip" },
      ]
    }
  ]
