---
name: 'Bug Report'
description: 'Report a bug in Apollo'
title: '[BUG]'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version you are using?
    validations:
      required: true
