name: Deployment

defaults:
  run:
    shell: bash
    
concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}
  cancel-in-progress: true
  
env:
  JAVA_VERSION: 11
  NODEJS_VERSION: 16.17.0
  ATALA_GITHUB_ACTOR: ${{ secrets.ATALA_GITHUB_ACTOR }}
  ATALA_GITHUB_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

on:
  workflow_dispatch:
  
jobs:
          
  deployment:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os-type: linux
          - os: macos-latest
            os-type: macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Install Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
          
      - name: Install NodeJS ${{ env.NODEJS_VERSION }}
        if: matrix.os-type == 'linux'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          
      - name: Publish Maven artifacts to Github Packages
        id: publish
        run: |
          if [ "${{ matrix.os-type }}" == "linux" ]; then
            ./gradlew publishAllPublicationsToGitHubPackagesRepository
          else
            ./gradlew publishIosArm64PublicationToGitHubPackagesRepository publishIosX64PublicationToGitHubPackagesRepository publishIosSimulatorArm64PublicationToGitHubPackagesRepository
          fi
